/* soapServer.c
   Generated by gSOAP 2.8.3 from cpe10.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapServer.c ver 2.8.3 2011-08-16 07:12:33 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:GetRPCMethods"))
		return soap_serve___cwmp1__GetRPCMethods(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:SetParameterValues"))
		return soap_serve___cwmp1__SetParameterValues(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:GetParameterValues"))
		return soap_serve___cwmp1__GetParameterValues(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:GetParameterNames"))
		return soap_serve___cwmp1__GetParameterNames(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:SetParameterAttributes"))
		return soap_serve___cwmp1__SetParameterAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:GetParameterAttributes"))
		return soap_serve___cwmp1__GetParameterAttributes(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:AddObject"))
		return soap_serve___cwmp1__AddObject(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:DeleteObject"))
		return soap_serve___cwmp1__DeleteObject(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:Download"))
		return soap_serve___cwmp1__Download(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:Reboot"))
		return soap_serve___cwmp1__Reboot(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:GetQueuedTransfers"))
		return soap_serve___cwmp1__GetQueuedTransfers(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:ScheduleInform"))
		return soap_serve___cwmp1__ScheduleInform(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:SetVouchers"))
		return soap_serve___cwmp1__SetVouchers(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:GetOptions"))
		return soap_serve___cwmp1__GetOptions(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:Upload"))
		return soap_serve___cwmp1__Upload(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:FactoryReset"))
		return soap_serve___cwmp1__FactoryReset(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:Inform"))
		return soap_serve___cwmp1__Inform(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:TransferComplete"))
		return soap_serve___cwmp1__TransferComplete(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:Kicked"))
		return soap_serve___cwmp1__Kicked(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:RequestDownload"))
		return soap_serve___cwmp1__RequestDownload(soap);
	if (!soap_match_tag(soap, soap->tag, "cwmp1:Fault"))
		return soap_serve___cwmp1__Fault(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetRPCMethods(struct soap *soap)
{	struct __cwmp1__GetRPCMethods soap_tmp___cwmp1__GetRPCMethods;
	struct _cwmp1__GetRPCMethodsResponse cwmp1__GetRPCMethodsResponse;
	soap_default__cwmp1__GetRPCMethodsResponse(soap, &cwmp1__GetRPCMethodsResponse);
	soap_default___cwmp1__GetRPCMethods(soap, &soap_tmp___cwmp1__GetRPCMethods);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__GetRPCMethods(soap, &soap_tmp___cwmp1__GetRPCMethods, "-cwmp1:GetRPCMethods", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__GetRPCMethods(soap, soap_tmp___cwmp1__GetRPCMethods.cwmp1__GetRPCMethods, &cwmp1__GetRPCMethodsResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__GetRPCMethodsResponse(soap, &cwmp1__GetRPCMethodsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__GetRPCMethodsResponse(soap, &cwmp1__GetRPCMethodsResponse, "cwmp1:GetRPCMethodsResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__GetRPCMethodsResponse(soap, &cwmp1__GetRPCMethodsResponse, "cwmp1:GetRPCMethodsResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__SetParameterValues(struct soap *soap)
{	struct __cwmp1__SetParameterValues soap_tmp___cwmp1__SetParameterValues;
	struct _cwmp1__SetParameterValuesResponse cwmp1__SetParameterValuesResponse;
	soap_default__cwmp1__SetParameterValuesResponse(soap, &cwmp1__SetParameterValuesResponse);
	soap_default___cwmp1__SetParameterValues(soap, &soap_tmp___cwmp1__SetParameterValues);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__SetParameterValues(soap, &soap_tmp___cwmp1__SetParameterValues, "-cwmp1:SetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__SetParameterValues(soap, soap_tmp___cwmp1__SetParameterValues.cwmp1__SetParameterValues, &cwmp1__SetParameterValuesResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__SetParameterValuesResponse(soap, &cwmp1__SetParameterValuesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__SetParameterValuesResponse(soap, &cwmp1__SetParameterValuesResponse, "cwmp1:SetParameterValuesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__SetParameterValuesResponse(soap, &cwmp1__SetParameterValuesResponse, "cwmp1:SetParameterValuesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetParameterValues(struct soap *soap)
{	struct __cwmp1__GetParameterValues soap_tmp___cwmp1__GetParameterValues;
	struct _cwmp1__GetParameterValuesResponse cwmp1__GetParameterValuesResponse;
	soap_default__cwmp1__GetParameterValuesResponse(soap, &cwmp1__GetParameterValuesResponse);
	soap_default___cwmp1__GetParameterValues(soap, &soap_tmp___cwmp1__GetParameterValues);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__GetParameterValues(soap, &soap_tmp___cwmp1__GetParameterValues, "-cwmp1:GetParameterValues", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__GetParameterValues(soap, soap_tmp___cwmp1__GetParameterValues.cwmp1__GetParameterValues, &cwmp1__GetParameterValuesResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__GetParameterValuesResponse(soap, &cwmp1__GetParameterValuesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__GetParameterValuesResponse(soap, &cwmp1__GetParameterValuesResponse, "cwmp1:GetParameterValuesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__GetParameterValuesResponse(soap, &cwmp1__GetParameterValuesResponse, "cwmp1:GetParameterValuesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetParameterNames(struct soap *soap)
{	struct __cwmp1__GetParameterNames soap_tmp___cwmp1__GetParameterNames;
	struct _cwmp1__GetParameterNamesResponse cwmp1__GetParameterNamesResponse;
	soap_default__cwmp1__GetParameterNamesResponse(soap, &cwmp1__GetParameterNamesResponse);
	soap_default___cwmp1__GetParameterNames(soap, &soap_tmp___cwmp1__GetParameterNames);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__GetParameterNames(soap, &soap_tmp___cwmp1__GetParameterNames, "-cwmp1:GetParameterNames", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__GetParameterNames(soap, soap_tmp___cwmp1__GetParameterNames.cwmp1__GetParameterNames, &cwmp1__GetParameterNamesResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__GetParameterNamesResponse(soap, &cwmp1__GetParameterNamesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__GetParameterNamesResponse(soap, &cwmp1__GetParameterNamesResponse, "cwmp1:GetParameterNamesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__GetParameterNamesResponse(soap, &cwmp1__GetParameterNamesResponse, "cwmp1:GetParameterNamesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__SetParameterAttributes(struct soap *soap)
{	struct __cwmp1__SetParameterAttributes soap_tmp___cwmp1__SetParameterAttributes;
	struct _cwmp1__SetParameterAttributesResponse cwmp1__SetParameterAttributesResponse;
	soap_default__cwmp1__SetParameterAttributesResponse(soap, &cwmp1__SetParameterAttributesResponse);
	soap_default___cwmp1__SetParameterAttributes(soap, &soap_tmp___cwmp1__SetParameterAttributes);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__SetParameterAttributes(soap, &soap_tmp___cwmp1__SetParameterAttributes, "-cwmp1:SetParameterAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__SetParameterAttributes(soap, soap_tmp___cwmp1__SetParameterAttributes.cwmp1__SetParameterAttributes, &cwmp1__SetParameterAttributesResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__SetParameterAttributesResponse(soap, &cwmp1__SetParameterAttributesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__SetParameterAttributesResponse(soap, &cwmp1__SetParameterAttributesResponse, "cwmp1:SetParameterAttributesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__SetParameterAttributesResponse(soap, &cwmp1__SetParameterAttributesResponse, "cwmp1:SetParameterAttributesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetParameterAttributes(struct soap *soap)
{	struct __cwmp1__GetParameterAttributes soap_tmp___cwmp1__GetParameterAttributes;
	struct _cwmp1__GetParameterAttributesResponse cwmp1__GetParameterAttributesResponse;
	soap_default__cwmp1__GetParameterAttributesResponse(soap, &cwmp1__GetParameterAttributesResponse);
	soap_default___cwmp1__GetParameterAttributes(soap, &soap_tmp___cwmp1__GetParameterAttributes);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__GetParameterAttributes(soap, &soap_tmp___cwmp1__GetParameterAttributes, "-cwmp1:GetParameterAttributes", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__GetParameterAttributes(soap, soap_tmp___cwmp1__GetParameterAttributes.cwmp1__GetParameterAttributes, &cwmp1__GetParameterAttributesResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__GetParameterAttributesResponse(soap, &cwmp1__GetParameterAttributesResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__GetParameterAttributesResponse(soap, &cwmp1__GetParameterAttributesResponse, "cwmp1:GetParameterAttributesResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__GetParameterAttributesResponse(soap, &cwmp1__GetParameterAttributesResponse, "cwmp1:GetParameterAttributesResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__AddObject(struct soap *soap)
{	struct __cwmp1__AddObject soap_tmp___cwmp1__AddObject;
	struct _cwmp1__AddObjectResponse cwmp1__AddObjectResponse;
	soap_default__cwmp1__AddObjectResponse(soap, &cwmp1__AddObjectResponse);
	soap_default___cwmp1__AddObject(soap, &soap_tmp___cwmp1__AddObject);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__AddObject(soap, &soap_tmp___cwmp1__AddObject, "-cwmp1:AddObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__AddObject(soap, soap_tmp___cwmp1__AddObject.cwmp1__AddObject, &cwmp1__AddObjectResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__AddObjectResponse(soap, &cwmp1__AddObjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__AddObjectResponse(soap, &cwmp1__AddObjectResponse, "cwmp1:AddObjectResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__AddObjectResponse(soap, &cwmp1__AddObjectResponse, "cwmp1:AddObjectResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__DeleteObject(struct soap *soap)
{	struct __cwmp1__DeleteObject soap_tmp___cwmp1__DeleteObject;
	struct _cwmp1__DeleteObjectResponse cwmp1__DeleteObjectResponse;
	soap_default__cwmp1__DeleteObjectResponse(soap, &cwmp1__DeleteObjectResponse);
	soap_default___cwmp1__DeleteObject(soap, &soap_tmp___cwmp1__DeleteObject);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__DeleteObject(soap, &soap_tmp___cwmp1__DeleteObject, "-cwmp1:DeleteObject", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__DeleteObject(soap, soap_tmp___cwmp1__DeleteObject.cwmp1__DeleteObject, &cwmp1__DeleteObjectResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__DeleteObjectResponse(soap, &cwmp1__DeleteObjectResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__DeleteObjectResponse(soap, &cwmp1__DeleteObjectResponse, "cwmp1:DeleteObjectResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__DeleteObjectResponse(soap, &cwmp1__DeleteObjectResponse, "cwmp1:DeleteObjectResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__Download(struct soap *soap)
{	struct __cwmp1__Download soap_tmp___cwmp1__Download;
	struct _cwmp1__DownloadResponse cwmp1__DownloadResponse;
	soap_default__cwmp1__DownloadResponse(soap, &cwmp1__DownloadResponse);
	soap_default___cwmp1__Download(soap, &soap_tmp___cwmp1__Download);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__Download(soap, &soap_tmp___cwmp1__Download, "-cwmp1:Download", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__Download(soap, soap_tmp___cwmp1__Download.cwmp1__Download, &cwmp1__DownloadResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__DownloadResponse(soap, &cwmp1__DownloadResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__DownloadResponse(soap, &cwmp1__DownloadResponse, "cwmp1:DownloadResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__DownloadResponse(soap, &cwmp1__DownloadResponse, "cwmp1:DownloadResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__Reboot(struct soap *soap)
{	struct __cwmp1__Reboot soap_tmp___cwmp1__Reboot;
	struct _cwmp1__RebootResponse cwmp1__RebootResponse;
	soap_default__cwmp1__RebootResponse(soap, &cwmp1__RebootResponse);
	soap_default___cwmp1__Reboot(soap, &soap_tmp___cwmp1__Reboot);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__Reboot(soap, &soap_tmp___cwmp1__Reboot, "-cwmp1:Reboot", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__Reboot(soap, soap_tmp___cwmp1__Reboot.cwmp1__Reboot, &cwmp1__RebootResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__RebootResponse(soap, &cwmp1__RebootResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__RebootResponse(soap, &cwmp1__RebootResponse, "cwmp1:RebootResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__RebootResponse(soap, &cwmp1__RebootResponse, "cwmp1:RebootResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetQueuedTransfers(struct soap *soap)
{	struct __cwmp1__GetQueuedTransfers soap_tmp___cwmp1__GetQueuedTransfers;
	struct _cwmp1__GetQueuedTransfersResponse cwmp1__GetQueuedTransfersResponse;
	soap_default__cwmp1__GetQueuedTransfersResponse(soap, &cwmp1__GetQueuedTransfersResponse);
	soap_default___cwmp1__GetQueuedTransfers(soap, &soap_tmp___cwmp1__GetQueuedTransfers);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__GetQueuedTransfers(soap, &soap_tmp___cwmp1__GetQueuedTransfers, "-cwmp1:GetQueuedTransfers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__GetQueuedTransfers(soap, soap_tmp___cwmp1__GetQueuedTransfers.cwmp1__GetQueuedTransfers, &cwmp1__GetQueuedTransfersResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__GetQueuedTransfersResponse(soap, &cwmp1__GetQueuedTransfersResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__GetQueuedTransfersResponse(soap, &cwmp1__GetQueuedTransfersResponse, "cwmp1:GetQueuedTransfersResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__GetQueuedTransfersResponse(soap, &cwmp1__GetQueuedTransfersResponse, "cwmp1:GetQueuedTransfersResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__ScheduleInform(struct soap *soap)
{	struct __cwmp1__ScheduleInform soap_tmp___cwmp1__ScheduleInform;
	struct _cwmp1__ScheduleInformResponse cwmp1__ScheduleInformResponse;
	soap_default__cwmp1__ScheduleInformResponse(soap, &cwmp1__ScheduleInformResponse);
	soap_default___cwmp1__ScheduleInform(soap, &soap_tmp___cwmp1__ScheduleInform);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__ScheduleInform(soap, &soap_tmp___cwmp1__ScheduleInform, "-cwmp1:ScheduleInform", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__ScheduleInform(soap, soap_tmp___cwmp1__ScheduleInform.cwmp1__ScheduleInform, &cwmp1__ScheduleInformResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__ScheduleInformResponse(soap, &cwmp1__ScheduleInformResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__ScheduleInformResponse(soap, &cwmp1__ScheduleInformResponse, "cwmp1:ScheduleInformResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__ScheduleInformResponse(soap, &cwmp1__ScheduleInformResponse, "cwmp1:ScheduleInformResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__SetVouchers(struct soap *soap)
{	struct __cwmp1__SetVouchers soap_tmp___cwmp1__SetVouchers;
	struct _cwmp1__SetVouchersResponse cwmp1__SetVouchersResponse;
	soap_default__cwmp1__SetVouchersResponse(soap, &cwmp1__SetVouchersResponse);
	soap_default___cwmp1__SetVouchers(soap, &soap_tmp___cwmp1__SetVouchers);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__SetVouchers(soap, &soap_tmp___cwmp1__SetVouchers, "-cwmp1:SetVouchers", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__SetVouchers(soap, soap_tmp___cwmp1__SetVouchers.cwmp1__SetVouchers, &cwmp1__SetVouchersResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__SetVouchersResponse(soap, &cwmp1__SetVouchersResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__SetVouchersResponse(soap, &cwmp1__SetVouchersResponse, "cwmp1:SetVouchersResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__SetVouchersResponse(soap, &cwmp1__SetVouchersResponse, "cwmp1:SetVouchersResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetOptions(struct soap *soap)
{	struct __cwmp1__GetOptions soap_tmp___cwmp1__GetOptions;
	struct _cwmp1__GetOptionsResponse cwmp1__GetOptionsResponse;
	soap_default__cwmp1__GetOptionsResponse(soap, &cwmp1__GetOptionsResponse);
	soap_default___cwmp1__GetOptions(soap, &soap_tmp___cwmp1__GetOptions);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__GetOptions(soap, &soap_tmp___cwmp1__GetOptions, "-cwmp1:GetOptions", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__GetOptions(soap, soap_tmp___cwmp1__GetOptions.cwmp1__GetOptions, &cwmp1__GetOptionsResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__GetOptionsResponse(soap, &cwmp1__GetOptionsResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__GetOptionsResponse(soap, &cwmp1__GetOptionsResponse, "cwmp1:GetOptionsResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__GetOptionsResponse(soap, &cwmp1__GetOptionsResponse, "cwmp1:GetOptionsResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__Upload(struct soap *soap)
{	struct __cwmp1__Upload soap_tmp___cwmp1__Upload;
	struct _cwmp1__UploadResponse cwmp1__UploadResponse;
	soap_default__cwmp1__UploadResponse(soap, &cwmp1__UploadResponse);
	soap_default___cwmp1__Upload(soap, &soap_tmp___cwmp1__Upload);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__Upload(soap, &soap_tmp___cwmp1__Upload, "-cwmp1:Upload", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__Upload(soap, soap_tmp___cwmp1__Upload.cwmp1__Upload, &cwmp1__UploadResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__UploadResponse(soap, &cwmp1__UploadResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__UploadResponse(soap, &cwmp1__UploadResponse, "cwmp1:UploadResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__UploadResponse(soap, &cwmp1__UploadResponse, "cwmp1:UploadResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__FactoryReset(struct soap *soap)
{	struct __cwmp1__FactoryReset soap_tmp___cwmp1__FactoryReset;
	struct _cwmp1__FactoryResetResponse cwmp1__FactoryResetResponse;
	soap_default__cwmp1__FactoryResetResponse(soap, &cwmp1__FactoryResetResponse);
	soap_default___cwmp1__FactoryReset(soap, &soap_tmp___cwmp1__FactoryReset);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__FactoryReset(soap, &soap_tmp___cwmp1__FactoryReset, "-cwmp1:FactoryReset", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__FactoryReset(soap, soap_tmp___cwmp1__FactoryReset.cwmp1__FactoryReset, &cwmp1__FactoryResetResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__FactoryResetResponse(soap, &cwmp1__FactoryResetResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__FactoryResetResponse(soap, &cwmp1__FactoryResetResponse, "cwmp1:FactoryResetResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__FactoryResetResponse(soap, &cwmp1__FactoryResetResponse, "cwmp1:FactoryResetResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__Inform(struct soap *soap)
{	struct __cwmp1__Inform soap_tmp___cwmp1__Inform;
	struct _cwmp1__InformResponse cwmp1__InformResponse;
	soap_default__cwmp1__InformResponse(soap, &cwmp1__InformResponse);
	soap_default___cwmp1__Inform(soap, &soap_tmp___cwmp1__Inform);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__Inform(soap, &soap_tmp___cwmp1__Inform, "-cwmp1:Inform", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__Inform(soap, soap_tmp___cwmp1__Inform.cwmp1__Inform, &cwmp1__InformResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__InformResponse(soap, &cwmp1__InformResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__InformResponse(soap, &cwmp1__InformResponse, "cwmp1:InformResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__InformResponse(soap, &cwmp1__InformResponse, "cwmp1:InformResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__TransferComplete(struct soap *soap)
{	struct __cwmp1__TransferComplete soap_tmp___cwmp1__TransferComplete;
	struct _cwmp1__TransferCompleteResponse cwmp1__TransferCompleteResponse;
	soap_default__cwmp1__TransferCompleteResponse(soap, &cwmp1__TransferCompleteResponse);
	soap_default___cwmp1__TransferComplete(soap, &soap_tmp___cwmp1__TransferComplete);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__TransferComplete(soap, &soap_tmp___cwmp1__TransferComplete, "-cwmp1:TransferComplete", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__TransferComplete(soap, soap_tmp___cwmp1__TransferComplete.cwmp1__TransferComplete, &cwmp1__TransferCompleteResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__TransferCompleteResponse(soap, &cwmp1__TransferCompleteResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__TransferCompleteResponse(soap, &cwmp1__TransferCompleteResponse, "cwmp1:TransferCompleteResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__TransferCompleteResponse(soap, &cwmp1__TransferCompleteResponse, "cwmp1:TransferCompleteResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__Kicked(struct soap *soap)
{	struct __cwmp1__Kicked soap_tmp___cwmp1__Kicked;
	struct _cwmp1__KickedResponse cwmp1__KickedResponse;
	soap_default__cwmp1__KickedResponse(soap, &cwmp1__KickedResponse);
	soap_default___cwmp1__Kicked(soap, &soap_tmp___cwmp1__Kicked);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__Kicked(soap, &soap_tmp___cwmp1__Kicked, "-cwmp1:Kicked", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__Kicked(soap, soap_tmp___cwmp1__Kicked.cwmp1__Kicked, &cwmp1__KickedResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__KickedResponse(soap, &cwmp1__KickedResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__KickedResponse(soap, &cwmp1__KickedResponse, "cwmp1:KickedResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__KickedResponse(soap, &cwmp1__KickedResponse, "cwmp1:KickedResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__RequestDownload(struct soap *soap)
{	struct __cwmp1__RequestDownload soap_tmp___cwmp1__RequestDownload;
	struct _cwmp1__RequestDownloadResponse cwmp1__RequestDownloadResponse;
	soap_default__cwmp1__RequestDownloadResponse(soap, &cwmp1__RequestDownloadResponse);
	soap_default___cwmp1__RequestDownload(soap, &soap_tmp___cwmp1__RequestDownload);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__RequestDownload(soap, &soap_tmp___cwmp1__RequestDownload, "-cwmp1:RequestDownload", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__RequestDownload(soap, soap_tmp___cwmp1__RequestDownload.cwmp1__RequestDownload, &cwmp1__RequestDownloadResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize__cwmp1__RequestDownloadResponse(soap, &cwmp1__RequestDownloadResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put__cwmp1__RequestDownloadResponse(soap, &cwmp1__RequestDownloadResponse, "cwmp1:RequestDownloadResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put__cwmp1__RequestDownloadResponse(soap, &cwmp1__RequestDownloadResponse, "cwmp1:RequestDownloadResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__Fault(struct soap *soap)
{	struct __cwmp1__Fault soap_tmp___cwmp1__Fault;
	soap_default___cwmp1__Fault(soap, &soap_tmp___cwmp1__Fault);
	soap->encodingStyle = NULL;
	if (!soap_get___cwmp1__Fault(soap, &soap_tmp___cwmp1__Fault, "-cwmp1:Fault", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __cwmp1__Fault(soap, soap_tmp___cwmp1__Fault.cwmp1__Fault);
	if (soap->error)
		return soap->error;
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.c */
