/* soapClient.c
   Generated by gSOAP 2.8.3 from cpetest.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"
#ifdef __cplusplus
extern "C" {
#endif

SOAP_SOURCE_STAMP("@(#) soapClient.c ver 2.8.3 2011-08-05 08:32:29 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetRPCMethods(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetRPCMethods *cwmp1__GetRPCMethods, struct _cwmp1__GetRPCMethodsResponse *cwmp1__GetRPCMethodsResponse)
{	struct __cwmp1__GetRPCMethods soap_tmp___cwmp1__GetRPCMethods;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getRPCMethodsIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__GetRPCMethods.cwmp1__GetRPCMethods = cwmp1__GetRPCMethods;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__GetRPCMethods(soap, &soap_tmp___cwmp1__GetRPCMethods);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__GetRPCMethods(soap, &soap_tmp___cwmp1__GetRPCMethods, "-cwmp1:GetRPCMethods", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__GetRPCMethods(soap, &soap_tmp___cwmp1__GetRPCMethods, "-cwmp1:GetRPCMethods", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__GetRPCMethodsResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__GetRPCMethodsResponse(soap, cwmp1__GetRPCMethodsResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__GetRPCMethodsResponse(soap, cwmp1__GetRPCMethodsResponse, "cwmp1:GetRPCMethodsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__SetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__SetParameterValues *cwmp1__SetParameterValues, struct _cwmp1__SetParameterValuesResponse *cwmp1__SetParameterValuesResponse)
{	struct __cwmp1__SetParameterValues soap_tmp___cwmp1__SetParameterValues;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:setParameterValuesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__SetParameterValues.cwmp1__SetParameterValues = cwmp1__SetParameterValues;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__SetParameterValues(soap, &soap_tmp___cwmp1__SetParameterValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__SetParameterValues(soap, &soap_tmp___cwmp1__SetParameterValues, "-cwmp1:SetParameterValues", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__SetParameterValues(soap, &soap_tmp___cwmp1__SetParameterValues, "-cwmp1:SetParameterValues", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__SetParameterValuesResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__SetParameterValuesResponse(soap, cwmp1__SetParameterValuesResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__SetParameterValuesResponse(soap, cwmp1__SetParameterValuesResponse, "cwmp1:SetParameterValuesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetParameterValues *cwmp1__GetParameterValues, struct _cwmp1__GetParameterValuesResponse *cwmp1__GetParameterValuesResponse)
{	struct __cwmp1__GetParameterValues soap_tmp___cwmp1__GetParameterValues;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getParameterValuesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__GetParameterValues.cwmp1__GetParameterValues = cwmp1__GetParameterValues;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__GetParameterValues(soap, &soap_tmp___cwmp1__GetParameterValues);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__GetParameterValues(soap, &soap_tmp___cwmp1__GetParameterValues, "-cwmp1:GetParameterValues", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__GetParameterValues(soap, &soap_tmp___cwmp1__GetParameterValues, "-cwmp1:GetParameterValues", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__GetParameterValuesResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__GetParameterValuesResponse(soap, cwmp1__GetParameterValuesResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__GetParameterValuesResponse(soap, cwmp1__GetParameterValuesResponse, "cwmp1:GetParameterValuesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetParameterNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetParameterNames *cwmp1__GetParameterNames, struct _cwmp1__GetParameterNamesResponse *cwmp1__GetParameterNamesResponse)
{	struct __cwmp1__GetParameterNames soap_tmp___cwmp1__GetParameterNames;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getParameterNamesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__GetParameterNames.cwmp1__GetParameterNames = cwmp1__GetParameterNames;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__GetParameterNames(soap, &soap_tmp___cwmp1__GetParameterNames);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__GetParameterNames(soap, &soap_tmp___cwmp1__GetParameterNames, "-cwmp1:GetParameterNames", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__GetParameterNames(soap, &soap_tmp___cwmp1__GetParameterNames, "-cwmp1:GetParameterNames", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__GetParameterNamesResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__GetParameterNamesResponse(soap, cwmp1__GetParameterNamesResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__GetParameterNamesResponse(soap, cwmp1__GetParameterNamesResponse, "cwmp1:GetParameterNamesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__SetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__SetParameterAttributes *cwmp1__SetParameterAttributes, struct _cwmp1__SetParameterAttributesResponse *cwmp1__SetParameterAttributesResponse)
{	struct __cwmp1__SetParameterAttributes soap_tmp___cwmp1__SetParameterAttributes;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:setParameterAttributesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__SetParameterAttributes.cwmp1__SetParameterAttributes = cwmp1__SetParameterAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__SetParameterAttributes(soap, &soap_tmp___cwmp1__SetParameterAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__SetParameterAttributes(soap, &soap_tmp___cwmp1__SetParameterAttributes, "-cwmp1:SetParameterAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__SetParameterAttributes(soap, &soap_tmp___cwmp1__SetParameterAttributes, "-cwmp1:SetParameterAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__SetParameterAttributesResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__SetParameterAttributesResponse(soap, cwmp1__SetParameterAttributesResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__SetParameterAttributesResponse(soap, cwmp1__SetParameterAttributesResponse, "cwmp1:SetParameterAttributesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetParameterAttributes *cwmp1__GetParameterAttributes, struct _cwmp1__GetParameterAttributesResponse *cwmp1__GetParameterAttributesResponse)
{	struct __cwmp1__GetParameterAttributes soap_tmp___cwmp1__GetParameterAttributes;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getParameterAttributesIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__GetParameterAttributes.cwmp1__GetParameterAttributes = cwmp1__GetParameterAttributes;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__GetParameterAttributes(soap, &soap_tmp___cwmp1__GetParameterAttributes);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__GetParameterAttributes(soap, &soap_tmp___cwmp1__GetParameterAttributes, "-cwmp1:GetParameterAttributes", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__GetParameterAttributes(soap, &soap_tmp___cwmp1__GetParameterAttributes, "-cwmp1:GetParameterAttributes", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__GetParameterAttributesResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__GetParameterAttributesResponse(soap, cwmp1__GetParameterAttributesResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__GetParameterAttributesResponse(soap, cwmp1__GetParameterAttributesResponse, "cwmp1:GetParameterAttributesResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__AddObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__AddObject *cwmp1__AddObject, struct _cwmp1__AddObjectResponse *cwmp1__AddObjectResponse)
{	struct __cwmp1__AddObject soap_tmp___cwmp1__AddObject;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:addObjectIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__AddObject.cwmp1__AddObject = cwmp1__AddObject;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__AddObject(soap, &soap_tmp___cwmp1__AddObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__AddObject(soap, &soap_tmp___cwmp1__AddObject, "-cwmp1:AddObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__AddObject(soap, &soap_tmp___cwmp1__AddObject, "-cwmp1:AddObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__AddObjectResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__AddObjectResponse(soap, cwmp1__AddObjectResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__AddObjectResponse(soap, cwmp1__AddObjectResponse, "cwmp1:AddObjectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__DeleteObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__DeleteObject *cwmp1__DeleteObject, struct _cwmp1__DeleteObjectResponse *cwmp1__DeleteObjectResponse)
{	struct __cwmp1__DeleteObject soap_tmp___cwmp1__DeleteObject;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:deleteObjectIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__DeleteObject.cwmp1__DeleteObject = cwmp1__DeleteObject;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__DeleteObject(soap, &soap_tmp___cwmp1__DeleteObject);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__DeleteObject(soap, &soap_tmp___cwmp1__DeleteObject, "-cwmp1:DeleteObject", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__DeleteObject(soap, &soap_tmp___cwmp1__DeleteObject, "-cwmp1:DeleteObject", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__DeleteObjectResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__DeleteObjectResponse(soap, cwmp1__DeleteObjectResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__DeleteObjectResponse(soap, cwmp1__DeleteObjectResponse, "cwmp1:DeleteObjectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__Download(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__Download *cwmp1__Download, struct _cwmp1__DownloadResponse *cwmp1__DownloadResponse)
{	struct __cwmp1__Download soap_tmp___cwmp1__Download;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:downloadIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__Download.cwmp1__Download = cwmp1__Download;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__Download(soap, &soap_tmp___cwmp1__Download);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__Download(soap, &soap_tmp___cwmp1__Download, "-cwmp1:Download", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__Download(soap, &soap_tmp___cwmp1__Download, "-cwmp1:Download", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__DownloadResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__DownloadResponse(soap, cwmp1__DownloadResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__DownloadResponse(soap, cwmp1__DownloadResponse, "cwmp1:DownloadResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__Reboot(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__Reboot *cwmp1__Reboot, struct _cwmp1__RebootResponse *cwmp1__RebootResponse)
{	struct __cwmp1__Reboot soap_tmp___cwmp1__Reboot;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:rebootIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__Reboot.cwmp1__Reboot = cwmp1__Reboot;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__Reboot(soap, &soap_tmp___cwmp1__Reboot);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__Reboot(soap, &soap_tmp___cwmp1__Reboot, "-cwmp1:Reboot", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__Reboot(soap, &soap_tmp___cwmp1__Reboot, "-cwmp1:Reboot", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__RebootResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__RebootResponse(soap, cwmp1__RebootResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__RebootResponse(soap, cwmp1__RebootResponse, "cwmp1:RebootResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetQueuedTransfers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetQueuedTransfers *cwmp1__GetQueuedTransfers, struct _cwmp1__GetQueuedTransfersResponse *cwmp1__GetQueuedTransfersResponse)
{	struct __cwmp1__GetQueuedTransfers soap_tmp___cwmp1__GetQueuedTransfers;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getQueuedTransfersIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__GetQueuedTransfers.cwmp1__GetQueuedTransfers = cwmp1__GetQueuedTransfers;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__GetQueuedTransfers(soap, &soap_tmp___cwmp1__GetQueuedTransfers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__GetQueuedTransfers(soap, &soap_tmp___cwmp1__GetQueuedTransfers, "-cwmp1:GetQueuedTransfers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__GetQueuedTransfers(soap, &soap_tmp___cwmp1__GetQueuedTransfers, "-cwmp1:GetQueuedTransfers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__GetQueuedTransfersResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__GetQueuedTransfersResponse(soap, cwmp1__GetQueuedTransfersResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__GetQueuedTransfersResponse(soap, cwmp1__GetQueuedTransfersResponse, "cwmp1:GetQueuedTransfersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__ScheduleInform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__ScheduleInform *cwmp1__ScheduleInform, struct _cwmp1__ScheduleInformResponse *cwmp1__ScheduleInformResponse)
{	struct __cwmp1__ScheduleInform soap_tmp___cwmp1__ScheduleInform;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:scheduleInformIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__ScheduleInform.cwmp1__ScheduleInform = cwmp1__ScheduleInform;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__ScheduleInform(soap, &soap_tmp___cwmp1__ScheduleInform);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__ScheduleInform(soap, &soap_tmp___cwmp1__ScheduleInform, "-cwmp1:ScheduleInform", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__ScheduleInform(soap, &soap_tmp___cwmp1__ScheduleInform, "-cwmp1:ScheduleInform", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__ScheduleInformResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__ScheduleInformResponse(soap, cwmp1__ScheduleInformResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__ScheduleInformResponse(soap, cwmp1__ScheduleInformResponse, "cwmp1:ScheduleInformResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__SetVouchers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__SetVouchers *cwmp1__SetVouchers, struct _cwmp1__SetVouchersResponse *cwmp1__SetVouchersResponse)
{	struct __cwmp1__SetVouchers soap_tmp___cwmp1__SetVouchers;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:setVouchersIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__SetVouchers.cwmp1__SetVouchers = cwmp1__SetVouchers;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__SetVouchers(soap, &soap_tmp___cwmp1__SetVouchers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__SetVouchers(soap, &soap_tmp___cwmp1__SetVouchers, "-cwmp1:SetVouchers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__SetVouchers(soap, &soap_tmp___cwmp1__SetVouchers, "-cwmp1:SetVouchers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__SetVouchersResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__SetVouchersResponse(soap, cwmp1__SetVouchersResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__SetVouchersResponse(soap, cwmp1__SetVouchersResponse, "cwmp1:SetVouchersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetOptions(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetOptions *cwmp1__GetOptions, struct _cwmp1__GetOptionsResponse *cwmp1__GetOptionsResponse)
{	struct __cwmp1__GetOptions soap_tmp___cwmp1__GetOptions;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getOptionsIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__GetOptions.cwmp1__GetOptions = cwmp1__GetOptions;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__GetOptions(soap, &soap_tmp___cwmp1__GetOptions);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__GetOptions(soap, &soap_tmp___cwmp1__GetOptions, "-cwmp1:GetOptions", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__GetOptions(soap, &soap_tmp___cwmp1__GetOptions, "-cwmp1:GetOptions", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__GetOptionsResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__GetOptionsResponse(soap, cwmp1__GetOptionsResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__GetOptionsResponse(soap, cwmp1__GetOptionsResponse, "cwmp1:GetOptionsResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__Upload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__Upload *cwmp1__Upload, struct _cwmp1__UploadResponse *cwmp1__UploadResponse)
{	struct __cwmp1__Upload soap_tmp___cwmp1__Upload;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:uploadIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__Upload.cwmp1__Upload = cwmp1__Upload;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__Upload(soap, &soap_tmp___cwmp1__Upload);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__Upload(soap, &soap_tmp___cwmp1__Upload, "-cwmp1:Upload", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__Upload(soap, &soap_tmp___cwmp1__Upload, "-cwmp1:Upload", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__UploadResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__UploadResponse(soap, cwmp1__UploadResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__UploadResponse(soap, cwmp1__UploadResponse, "cwmp1:UploadResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__FactoryReset(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__FactoryReset *cwmp1__FactoryReset, struct _cwmp1__FactoryResetResponse *cwmp1__FactoryResetResponse)
{	struct __cwmp1__FactoryReset soap_tmp___cwmp1__FactoryReset;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:factoryResetIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__FactoryReset.cwmp1__FactoryReset = cwmp1__FactoryReset;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__FactoryReset(soap, &soap_tmp___cwmp1__FactoryReset);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__FactoryReset(soap, &soap_tmp___cwmp1__FactoryReset, "-cwmp1:FactoryReset", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__FactoryReset(soap, &soap_tmp___cwmp1__FactoryReset, "-cwmp1:FactoryReset", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__FactoryResetResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__FactoryResetResponse(soap, cwmp1__FactoryResetResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__FactoryResetResponse(soap, cwmp1__FactoryResetResponse, "cwmp1:FactoryResetResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetAllQueuedTransfers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetAllQueuedTransfers *cwmp1__GetAllQueuedTransfers, struct _cwmp1__GetAllQueuedTransfersResponse *cwmp1__GetAllQueuedTransfersResponse)
{	struct __cwmp1__GetAllQueuedTransfers soap_tmp___cwmp1__GetAllQueuedTransfers;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:getAllQueuedTransfersIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__GetAllQueuedTransfers.cwmp1__GetAllQueuedTransfers = cwmp1__GetAllQueuedTransfers;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__GetAllQueuedTransfers(soap, &soap_tmp___cwmp1__GetAllQueuedTransfers);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__GetAllQueuedTransfers(soap, &soap_tmp___cwmp1__GetAllQueuedTransfers, "-cwmp1:GetAllQueuedTransfers", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__GetAllQueuedTransfers(soap, &soap_tmp___cwmp1__GetAllQueuedTransfers, "-cwmp1:GetAllQueuedTransfers", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__GetAllQueuedTransfersResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__GetAllQueuedTransfersResponse(soap, cwmp1__GetAllQueuedTransfersResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__GetAllQueuedTransfersResponse(soap, cwmp1__GetAllQueuedTransfersResponse, "cwmp1:GetAllQueuedTransfersResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__Inform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__Inform *cwmp1__Inform, struct _cwmp1__InformResponse *cwmp1__InformResponse)
{	struct __cwmp1__Inform soap_tmp___cwmp1__Inform;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:informIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__Inform.cwmp1__Inform = cwmp1__Inform;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__Inform(soap, &soap_tmp___cwmp1__Inform);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__Inform(soap, &soap_tmp___cwmp1__Inform, "-cwmp1:Inform", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__Inform(soap, &soap_tmp___cwmp1__Inform, "-cwmp1:Inform", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__InformResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__InformResponse(soap, cwmp1__InformResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__InformResponse(soap, cwmp1__InformResponse, "cwmp1:InformResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__TransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__TransferComplete *cwmp1__TransferComplete, struct _cwmp1__TransferCompleteResponse *cwmp1__TransferCompleteResponse)
{	struct __cwmp1__TransferComplete soap_tmp___cwmp1__TransferComplete;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:transferCompleteIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__TransferComplete.cwmp1__TransferComplete = cwmp1__TransferComplete;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__TransferComplete(soap, &soap_tmp___cwmp1__TransferComplete);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__TransferComplete(soap, &soap_tmp___cwmp1__TransferComplete, "-cwmp1:TransferComplete", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__TransferComplete(soap, &soap_tmp___cwmp1__TransferComplete, "-cwmp1:TransferComplete", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__TransferCompleteResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__TransferCompleteResponse(soap, cwmp1__TransferCompleteResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__TransferCompleteResponse(soap, cwmp1__TransferCompleteResponse, "cwmp1:TransferCompleteResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__AutonomousTransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__AutonomousTransferComplete *cwmp1__AutonomousTransferComplete, struct _cwmp1__AutonomousTransferCompleteResponse *cwmp1__AutonomousTransferCompleteResponse)
{	struct __cwmp1__AutonomousTransferComplete soap_tmp___cwmp1__AutonomousTransferComplete;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:autonomousTransferCompleteIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__AutonomousTransferComplete.cwmp1__AutonomousTransferComplete = cwmp1__AutonomousTransferComplete;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__AutonomousTransferComplete(soap, &soap_tmp___cwmp1__AutonomousTransferComplete);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__AutonomousTransferComplete(soap, &soap_tmp___cwmp1__AutonomousTransferComplete, "-cwmp1:AutonomousTransferComplete", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__AutonomousTransferComplete(soap, &soap_tmp___cwmp1__AutonomousTransferComplete, "-cwmp1:AutonomousTransferComplete", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__AutonomousTransferCompleteResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__AutonomousTransferCompleteResponse(soap, cwmp1__AutonomousTransferCompleteResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__AutonomousTransferCompleteResponse(soap, cwmp1__AutonomousTransferCompleteResponse, "cwmp1:AutonomousTransferCompleteResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__Kicked(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__Kicked *cwmp1__Kicked, struct _cwmp1__KickedResponse *cwmp1__KickedResponse)
{	struct __cwmp1__Kicked soap_tmp___cwmp1__Kicked;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:kickedIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__Kicked.cwmp1__Kicked = cwmp1__Kicked;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__Kicked(soap, &soap_tmp___cwmp1__Kicked);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__Kicked(soap, &soap_tmp___cwmp1__Kicked, "-cwmp1:Kicked", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__Kicked(soap, &soap_tmp___cwmp1__Kicked, "-cwmp1:Kicked", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__KickedResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__KickedResponse(soap, cwmp1__KickedResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__KickedResponse(soap, cwmp1__KickedResponse, "cwmp1:KickedResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__RequestDownload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__RequestDownload *cwmp1__RequestDownload, struct _cwmp1__RequestDownloadResponse *cwmp1__RequestDownloadResponse)
{	struct __cwmp1__RequestDownload soap_tmp___cwmp1__RequestDownload;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:requestDownloadIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__RequestDownload.cwmp1__RequestDownload = cwmp1__RequestDownload;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__RequestDownload(soap, &soap_tmp___cwmp1__RequestDownload);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__RequestDownload(soap, &soap_tmp___cwmp1__RequestDownload, "-cwmp1:RequestDownload", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__RequestDownload(soap, &soap_tmp___cwmp1__RequestDownload, "-cwmp1:RequestDownload", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!cwmp1__RequestDownloadResponse)
		return soap_closesock(soap);
	soap_default__cwmp1__RequestDownloadResponse(soap, cwmp1__RequestDownloadResponse);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get__cwmp1__RequestDownloadResponse(soap, cwmp1__RequestDownloadResponse, "cwmp1:RequestDownloadResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp1__Fault(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__Fault *cwmp1__Fault)
{	struct __cwmp1__Fault soap_tmp___cwmp1__Fault;
	if (!soap_action)
		soap_action = "urn:dslforum-org:cwmp-1-1:faultIn";
	soap->encodingStyle = NULL;
	soap_tmp___cwmp1__Fault.cwmp1__Fault = cwmp1__Fault;
	soap_begin(soap);
	soap_serializeheader(soap);
	soap_serialize___cwmp1__Fault(soap, &soap_tmp___cwmp1__Fault);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___cwmp1__Fault(soap, &soap_tmp___cwmp1__Fault, "-cwmp1:Fault", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_endpoint, soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___cwmp1__Fault(soap, &soap_tmp___cwmp1__Fault, "-cwmp1:Fault", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp1__Fault(struct soap *soap, struct __cwmp1__Fault *_param_1)
{
	soap_default___cwmp1__Fault(soap, _param_1);
	soap_begin(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_get___cwmp1__Fault(soap, _param_1, "-cwmp1:Fault", NULL);
	if (soap->error == SOAP_TAG_MISMATCH && soap->level == 2)
		soap->error = SOAP_NO_METHOD;
	if (soap->error
	 || soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

#ifdef __cplusplus
}
#endif

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.c */
