/* soapStub.h
   Generated by gSOAP 2.8.3 from cpetest.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#define SOAP_NAMESPACE_OF_cwmp2	""
#define SOAP_NAMESPACE_OF_cwmp1	"urn:dslforum-org:cwmp-1-1"
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (12)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

#ifndef SOAP_TYPE__cwmp1__SetParameterAttributesStruct_Notification
#define SOAP_TYPE__cwmp1__SetParameterAttributesStruct_Notification (24)
/* cwmp1:SetParameterAttributesStruct-Notification */
enum _cwmp1__SetParameterAttributesStruct_Notification {_cwmp1__SetParameterAttributesStruct_Notification__0 = 0, _cwmp1__SetParameterAttributesStruct_Notification__1 = 1, _cwmp1__SetParameterAttributesStruct_Notification__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp1__ParameterAttributeStruct_Notification
#define SOAP_TYPE__cwmp1__ParameterAttributeStruct_Notification (28)
/* cwmp1:ParameterAttributeStruct-Notification */
enum _cwmp1__ParameterAttributeStruct_Notification {_cwmp1__ParameterAttributeStruct_Notification__0 = 0, _cwmp1__ParameterAttributeStruct_Notification__1 = 1, _cwmp1__ParameterAttributeStruct_Notification__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp1__QueuedTransferStruct_State
#define SOAP_TYPE__cwmp1__QueuedTransferStruct_State (30)
/* cwmp1:QueuedTransferStruct-State */
enum _cwmp1__QueuedTransferStruct_State {_cwmp1__QueuedTransferStruct_State__1 = 1, _cwmp1__QueuedTransferStruct_State__2 = 2, _cwmp1__QueuedTransferStruct_State__3 = 3};
#endif

#ifndef SOAP_TYPE__cwmp1__AllQueuedTransferStruct_State
#define SOAP_TYPE__cwmp1__AllQueuedTransferStruct_State (32)
/* cwmp1:AllQueuedTransferStruct-State */
enum _cwmp1__AllQueuedTransferStruct_State {_cwmp1__AllQueuedTransferStruct_State__1 = 1, _cwmp1__AllQueuedTransferStruct_State__2 = 2, _cwmp1__AllQueuedTransferStruct_State__3 = 3};
#endif

#ifndef SOAP_TYPE__cwmp1__OptionStruct_State
#define SOAP_TYPE__cwmp1__OptionStruct_State (35)
/* cwmp1:OptionStruct-State */
enum _cwmp1__OptionStruct_State {_cwmp1__OptionStruct_State__0 = 0, _cwmp1__OptionStruct_State__1 = 1, _cwmp1__OptionStruct_State__2 = 2, _cwmp1__OptionStruct_State__3 = 3};
#endif

#ifndef SOAP_TYPE__cwmp1__OptionStruct_Mode
#define SOAP_TYPE__cwmp1__OptionStruct_Mode (36)
/* cwmp1:OptionStruct-Mode */
enum _cwmp1__OptionStruct_Mode {_cwmp1__OptionStruct_Mode__0 = 0, _cwmp1__OptionStruct_Mode__1 = 1, _cwmp1__OptionStruct_Mode__2 = 2};
#endif

#ifndef SOAP_TYPE__cwmp1__OptionStruct_IsTransferable
#define SOAP_TYPE__cwmp1__OptionStruct_IsTransferable (39)
/* cwmp1:OptionStruct-IsTransferable */
enum _cwmp1__OptionStruct_IsTransferable {_cwmp1__OptionStruct_IsTransferable__0 = 0, _cwmp1__OptionStruct_IsTransferable__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp1__SetParameterValuesResponse_Status
#define SOAP_TYPE__cwmp1__SetParameterValuesResponse_Status (51)
/* cwmp1:SetParameterValuesResponse-Status */
enum _cwmp1__SetParameterValuesResponse_Status {_cwmp1__SetParameterValuesResponse_Status__0 = 0, _cwmp1__SetParameterValuesResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp1__AddObjectResponse_Status
#define SOAP_TYPE__cwmp1__AddObjectResponse_Status (70)
/* cwmp1:AddObjectResponse-Status */
enum _cwmp1__AddObjectResponse_Status {_cwmp1__AddObjectResponse_Status__0 = 0, _cwmp1__AddObjectResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp1__DeleteObjectResponse_Status
#define SOAP_TYPE__cwmp1__DeleteObjectResponse_Status (73)
/* cwmp1:DeleteObjectResponse-Status */
enum _cwmp1__DeleteObjectResponse_Status {_cwmp1__DeleteObjectResponse_Status__0 = 0, _cwmp1__DeleteObjectResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp1__DownloadResponse_Status
#define SOAP_TYPE__cwmp1__DownloadResponse_Status (76)
/* cwmp1:DownloadResponse-Status */
enum _cwmp1__DownloadResponse_Status {_cwmp1__DownloadResponse_Status__0 = 0, _cwmp1__DownloadResponse_Status__1 = 1};
#endif

#ifndef SOAP_TYPE__cwmp1__UploadResponse_Status
#define SOAP_TYPE__cwmp1__UploadResponse_Status (95)
/* cwmp1:UploadResponse-Status */
enum _cwmp1__UploadResponse_Status {_cwmp1__UploadResponse_Status__0 = 0, _cwmp1__UploadResponse_Status__1 = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE_SOAP_ENC__base64
#define SOAP_TYPE_SOAP_ENC__base64 (7)
/* Base64 schema type: */
struct SOAP_ENC__base64
{
	unsigned char *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1__FaultStruct
#define SOAP_TYPE_cwmp1__FaultStruct (17)
/* cwmp1:FaultStruct */
struct cwmp1__FaultStruct
{
	char *FaultCode;	/* required element of type xsd:string */
	char *FaultString;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp1__DeviceIdStruct
#define SOAP_TYPE_cwmp1__DeviceIdStruct (18)
/* cwmp1:DeviceIdStruct */
struct cwmp1__DeviceIdStruct
{
	char *Manufacturer;	/* required element of type xsd:string */
	char *OUI;	/* required element of type xsd:string */
	char *ProductClass;	/* required element of type xsd:string */
	char *SerialNumber;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp1__EventStruct
#define SOAP_TYPE_cwmp1__EventStruct (19)
/* cwmp1:EventStruct */
struct cwmp1__EventStruct
{
	char *EventCode;	/* required element of type xsd:string */
	char *CommandKey;	/* required element of type cwmp1:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE_cwmp1__ParameterValueStruct
#define SOAP_TYPE_cwmp1__ParameterValueStruct (20)
/* cwmp1:ParameterValueStruct */
struct cwmp1__ParameterValueStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:anySimpleType */
};
#endif

#ifndef SOAP_TYPE_cwmp1__ParameterInfoStruct
#define SOAP_TYPE_cwmp1__ParameterInfoStruct (21)
/* cwmp1:ParameterInfoStruct */
struct cwmp1__ParameterInfoStruct
{
	char *Name;	/* required element of type xsd:string */
	enum xsd__boolean Writable;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_cwmp1__SetParameterAttributesStruct
#define SOAP_TYPE_cwmp1__SetParameterAttributesStruct (22)
/* cwmp1:SetParameterAttributesStruct */
struct cwmp1__SetParameterAttributesStruct
{
	char **Name;	/* optional element of type xsd:string */
	enum xsd__boolean NotificationChange;	/* required element of type xsd:boolean */
	enum _cwmp1__SetParameterAttributesStruct_Notification Notification;	/* required element of type cwmp1:SetParameterAttributesStruct-Notification */
	enum xsd__boolean AccessListChange;	/* required element of type xsd:boolean */
	struct cwmp1AccessList *AccessList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp1__ParameterAttributeStruct
#define SOAP_TYPE_cwmp1__ParameterAttributeStruct (27)
/* cwmp1:ParameterAttributeStruct */
struct cwmp1__ParameterAttributeStruct
{
	char *Name;	/* required element of type xsd:string */
	enum _cwmp1__ParameterAttributeStruct_Notification Notification;	/* required element of type cwmp1:ParameterAttributeStruct-Notification */
	struct cwmp1AccessList *AccessList;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_cwmp1__QueuedTransferStruct
#define SOAP_TYPE_cwmp1__QueuedTransferStruct (29)
/* cwmp1:QueuedTransferStruct */
struct cwmp1__QueuedTransferStruct
{
	char *CommandKey;	/* required element of type cwmp1:CommandKeyType */
	enum _cwmp1__QueuedTransferStruct_State State;	/* required element of type cwmp1:QueuedTransferStruct-State */
};
#endif

#ifndef SOAP_TYPE_cwmp1__AllQueuedTransferStruct
#define SOAP_TYPE_cwmp1__AllQueuedTransferStruct (31)
/* cwmp1:AllQueuedTransferStruct */
struct cwmp1__AllQueuedTransferStruct
{
	char *CommandKey;	/* required element of type cwmp1:CommandKeyType */
	enum _cwmp1__AllQueuedTransferStruct_State State;	/* required element of type cwmp1:AllQueuedTransferStruct-State */
	enum xsd__boolean IsDownload;	/* required element of type xsd:boolean */
	char *FileType;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp1__ArgStruct
#define SOAP_TYPE_cwmp1__ArgStruct (33)
/* cwmp1:ArgStruct */
struct cwmp1__ArgStruct
{
	char *Name;	/* required element of type xsd:string */
	char *Value;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_cwmp1__OptionStruct
#define SOAP_TYPE_cwmp1__OptionStruct (34)
/* cwmp1:OptionStruct */
struct cwmp1__OptionStruct
{
	char *OptionName;	/* required element of type xsd:string */
	unsigned int VoucherSN;	/* required element of type xsd:unsignedInt */
	enum _cwmp1__OptionStruct_State State;	/* required element of type cwmp1:OptionStruct-State */
	enum _cwmp1__OptionStruct_Mode Mode;	/* required element of type cwmp1:OptionStruct-Mode */
	time_t StartDate;	/* required element of type xsd:dateTime */
	time_t *ExpirationDate;	/* optional element of type xsd:dateTime */
	enum _cwmp1__OptionStruct_IsTransferable IsTransferable;	/* required element of type cwmp1:OptionStruct-IsTransferable */
};
#endif

#ifndef SOAP_TYPE__cwmp1__Fault_SetParameterValuesFault
#define SOAP_TYPE__cwmp1__Fault_SetParameterValuesFault (41)
/* cwmp1:Fault-SetParameterValuesFault */
struct _cwmp1__Fault_SetParameterValuesFault
{
	char *ParameterName;	/* required element of type xsd:string */
	char *FaultCode;	/* required element of type cwmp1:FaultCodeType */
	char *FaultString;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp1__Fault
#define SOAP_TYPE__cwmp1__Fault (40)
/* cwmp1:Fault */
struct _cwmp1__Fault
{
	char *FaultCode;	/* required element of type cwmp1:FaultCodeType */
	char *FaultString;	/* optional element of type xsd:string */
	int __sizeSetParameterValuesFault;	/* sequence of elements <SetParameterValuesFault> */
	struct _cwmp1__Fault_SetParameterValuesFault *SetParameterValuesFault;	/* optional element of type cwmp1:Fault-SetParameterValuesFault */
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetRPCMethods
#define SOAP_TYPE__cwmp1__GetRPCMethods (43)
/* cwmp1:GetRPCMethods */
struct _cwmp1__GetRPCMethods
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetRPCMethodsResponse
#define SOAP_TYPE__cwmp1__GetRPCMethodsResponse (44)
/* cwmp1:GetRPCMethodsResponse */
struct _cwmp1__GetRPCMethodsResponse
{
	struct cwmp1MethodList *MethodList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp1__SetParameterValues
#define SOAP_TYPE__cwmp1__SetParameterValues (47)
/* cwmp1:SetParameterValues */
struct _cwmp1__SetParameterValues
{
	struct cwmp1ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
	char *ParameterKey;	/* required element of type cwmp1:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp1__SetParameterValuesResponse
#define SOAP_TYPE__cwmp1__SetParameterValuesResponse (50)
/* cwmp1:SetParameterValuesResponse */
struct _cwmp1__SetParameterValuesResponse
{
	enum _cwmp1__SetParameterValuesResponse_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp1:SetParameterValuesResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetParameterValues
#define SOAP_TYPE__cwmp1__GetParameterValues (52)
/* cwmp1:GetParameterValues */
struct _cwmp1__GetParameterValues
{
	struct cwmp1ParameterNames *ParameterNames;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetParameterValuesResponse
#define SOAP_TYPE__cwmp1__GetParameterValuesResponse (55)
/* cwmp1:GetParameterValuesResponse */
struct _cwmp1__GetParameterValuesResponse
{
	struct cwmp1ParameterValueList *ParameterList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetParameterNames
#define SOAP_TYPE__cwmp1__GetParameterNames (56)
/* cwmp1:GetParameterNames */
struct _cwmp1__GetParameterNames
{
	char **ParameterPath;	/* optional element of type xsd:string */
	enum xsd__boolean NextLevel;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetParameterNamesResponse
#define SOAP_TYPE__cwmp1__GetParameterNamesResponse (57)
/* cwmp1:GetParameterNamesResponse */
struct _cwmp1__GetParameterNamesResponse
{
	struct cwmp1ParameterInfoList *ParameterList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfParameterInfoStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp1__SetParameterAttributes
#define SOAP_TYPE__cwmp1__SetParameterAttributes (60)
/* cwmp1:SetParameterAttributes */
struct _cwmp1__SetParameterAttributes
{
	struct cwmp1SetParameterAttributesList *ParameterList;	/* required element of type ArrayOfSetParameterAttributesStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp1__SetParameterAttributesResponse
#define SOAP_TYPE__cwmp1__SetParameterAttributesResponse (63)
/* cwmp1:SetParameterAttributesResponse */
struct _cwmp1__SetParameterAttributesResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetParameterAttributes
#define SOAP_TYPE__cwmp1__GetParameterAttributes (64)
/* cwmp1:GetParameterAttributes */
struct _cwmp1__GetParameterAttributes
{
	struct cwmp1ParameterNames *ParameterNames;	/* required element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetParameterAttributesResponse
#define SOAP_TYPE__cwmp1__GetParameterAttributesResponse (65)
/* cwmp1:GetParameterAttributesResponse */
struct _cwmp1__GetParameterAttributesResponse
{
	struct cwmp1ParameterAttributeList *ParameterList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfParameterAttributeStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp1__AddObject
#define SOAP_TYPE__cwmp1__AddObject (68)
/* cwmp1:AddObject */
struct _cwmp1__AddObject
{
	char *ObjectName;	/* required element of type cwmp1:ObjectNameType */
	char *ParameterKey;	/* required element of type cwmp1:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp1__AddObjectResponse
#define SOAP_TYPE__cwmp1__AddObjectResponse (69)
/* cwmp1:AddObjectResponse */
struct _cwmp1__AddObjectResponse
{
	unsigned int InstanceNumber;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
	enum _cwmp1__AddObjectResponse_Status Status;	/* required element of type cwmp1:AddObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp1__DeleteObject
#define SOAP_TYPE__cwmp1__DeleteObject (71)
/* cwmp1:DeleteObject */
struct _cwmp1__DeleteObject
{
	char *ObjectName;	/* required element of type cwmp1:ObjectNameType */
	char *ParameterKey;	/* required element of type cwmp1:ParameterKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp1__DeleteObjectResponse
#define SOAP_TYPE__cwmp1__DeleteObjectResponse (72)
/* cwmp1:DeleteObjectResponse */
struct _cwmp1__DeleteObjectResponse
{
	enum _cwmp1__DeleteObjectResponse_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp1:DeleteObjectResponse-Status */
};
#endif

#ifndef SOAP_TYPE__cwmp1__Download
#define SOAP_TYPE__cwmp1__Download (74)
/* cwmp1:Download */
struct _cwmp1__Download
{
	char *CommandKey;	/* required element of type cwmp1:CommandKeyType */
	char *FileType;	/* required element of type xsd:string */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
	char *SuccessURL;	/* required element of type xsd:string */
	char *FailureURL;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp1__DownloadResponse
#define SOAP_TYPE__cwmp1__DownloadResponse (75)
/* cwmp1:DownloadResponse */
struct _cwmp1__DownloadResponse
{
	enum _cwmp1__DownloadResponse_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp1:DownloadResponse-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp1__Reboot
#define SOAP_TYPE__cwmp1__Reboot (77)
/* cwmp1:Reboot */
struct _cwmp1__Reboot
{
	char *CommandKey;	/* required element of type cwmp1:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp1__RebootResponse
#define SOAP_TYPE__cwmp1__RebootResponse (78)
/* cwmp1:RebootResponse */
struct _cwmp1__RebootResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetQueuedTransfers
#define SOAP_TYPE__cwmp1__GetQueuedTransfers (79)
/* cwmp1:GetQueuedTransfers */
struct _cwmp1__GetQueuedTransfers
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetQueuedTransfersResponse
#define SOAP_TYPE__cwmp1__GetQueuedTransfersResponse (80)
/* cwmp1:GetQueuedTransfersResponse */
struct _cwmp1__GetQueuedTransfersResponse
{
	struct cwmp1TransferList *TransferList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfQueuedTransferStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp1__ScheduleInform
#define SOAP_TYPE__cwmp1__ScheduleInform (83)
/* cwmp1:ScheduleInform */
struct _cwmp1__ScheduleInform
{
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
	char *CommandKey;	/* required element of type cwmp1:CommandKeyType */
};
#endif

#ifndef SOAP_TYPE__cwmp1__ScheduleInformResponse
#define SOAP_TYPE__cwmp1__ScheduleInformResponse (84)
/* cwmp1:ScheduleInformResponse */
struct _cwmp1__ScheduleInformResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp1__SetVouchers
#define SOAP_TYPE__cwmp1__SetVouchers (85)
/* cwmp1:SetVouchers */
struct _cwmp1__SetVouchers
{
	struct cwmp1VoucherList *VoucherList;	/* required element of type ArrayOfbase64 */
};
#endif

#ifndef SOAP_TYPE__cwmp1__SetVouchersResponse
#define SOAP_TYPE__cwmp1__SetVouchersResponse (88)
/* cwmp1:SetVouchersResponse */
struct _cwmp1__SetVouchersResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetOptions
#define SOAP_TYPE__cwmp1__GetOptions (89)
/* cwmp1:GetOptions */
struct _cwmp1__GetOptions
{
	char *OptionName;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetOptionsResponse
#define SOAP_TYPE__cwmp1__GetOptionsResponse (90)
/* cwmp1:GetOptionsResponse */
struct _cwmp1__GetOptionsResponse
{
	struct cwmp1OptionList *OptionList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfOptionStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp1__Upload
#define SOAP_TYPE__cwmp1__Upload (93)
/* cwmp1:Upload */
struct _cwmp1__Upload
{
	char *CommandKey;	/* required element of type cwmp1:CommandKeyType */
	char *FileType;	/* required element of type xsd:string */
	char *URL;	/* required element of type xsd:string */
	char *Username;	/* required element of type xsd:string */
	char *Password;	/* required element of type xsd:string */
	unsigned int DelaySeconds;	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__cwmp1__UploadResponse
#define SOAP_TYPE__cwmp1__UploadResponse (94)
/* cwmp1:UploadResponse */
struct _cwmp1__UploadResponse
{
	enum _cwmp1__UploadResponse_Status Status;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type cwmp1:UploadResponse-Status */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp1__FactoryReset
#define SOAP_TYPE__cwmp1__FactoryReset (96)
/* cwmp1:FactoryReset */
struct _cwmp1__FactoryReset
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp1__FactoryResetResponse
#define SOAP_TYPE__cwmp1__FactoryResetResponse (97)
/* cwmp1:FactoryResetResponse */
struct _cwmp1__FactoryResetResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetAllQueuedTransfers
#define SOAP_TYPE__cwmp1__GetAllQueuedTransfers (98)
/* cwmp1:GetAllQueuedTransfers */
struct _cwmp1__GetAllQueuedTransfers
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp1__GetAllQueuedTransfersResponse
#define SOAP_TYPE__cwmp1__GetAllQueuedTransfersResponse (99)
/* cwmp1:GetAllQueuedTransfersResponse */
struct _cwmp1__GetAllQueuedTransfersResponse
{
	struct cwmp1AllTransferList *TransferList;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type ArrayOfAllQueuedTransferStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp1__Inform
#define SOAP_TYPE__cwmp1__Inform (102)
/* cwmp1:Inform */
struct _cwmp1__Inform
{
	struct cwmp1__DeviceIdStruct *DeviceId;	/* required element of type cwmp1:DeviceIdStruct */
	struct cwmp1EventList *Event;	/* required element of type ArrayOfEventStruct */
	unsigned int MaxEnvelopes;	/* required element of type xsd:unsignedInt */
	time_t CurrentTime;	/* required element of type xsd:dateTime */
	unsigned int RetryCount;	/* required element of type xsd:unsignedInt */
	struct cwmp1ParameterValueList *ParameterList;	/* required element of type ArrayOfParameterValueStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp1__InformResponse
#define SOAP_TYPE__cwmp1__InformResponse (106)
/* cwmp1:InformResponse */
struct _cwmp1__InformResponse
{
	unsigned int MaxEnvelopes;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:unsignedInt */
};
#endif

#ifndef SOAP_TYPE__cwmp1__TransferComplete
#define SOAP_TYPE__cwmp1__TransferComplete (107)
/* cwmp1:TransferComplete */
struct _cwmp1__TransferComplete
{
	char *CommandKey;	/* required element of type cwmp1:CommandKeyType */
	struct cwmp1__FaultStruct *FaultStruct;	/* required element of type cwmp1:FaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp1__TransferCompleteResponse
#define SOAP_TYPE__cwmp1__TransferCompleteResponse (109)
/* cwmp1:TransferCompleteResponse */
struct _cwmp1__TransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp1__AutonomousTransferComplete
#define SOAP_TYPE__cwmp1__AutonomousTransferComplete (110)
/* cwmp1:AutonomousTransferComplete */
struct _cwmp1__AutonomousTransferComplete
{
	char *AnnounceURL;	/* required element of type xsd:string */
	char *TransferURL;	/* required element of type xsd:string */
	enum xsd__boolean IsDownload;	/* required element of type xsd:boolean */
	char *FileType;	/* required element of type xsd:string */
	unsigned int FileSize;	/* required element of type xsd:unsignedInt */
	char *TargetFileName;	/* required element of type xsd:string */
	struct cwmp1__FaultStruct *FaultStruct;	/* required element of type cwmp1:FaultStruct */
	time_t StartTime;	/* required element of type xsd:dateTime */
	time_t CompleteTime;	/* required element of type xsd:dateTime */
};
#endif

#ifndef SOAP_TYPE__cwmp1__AutonomousTransferCompleteResponse
#define SOAP_TYPE__cwmp1__AutonomousTransferCompleteResponse (111)
/* cwmp1:AutonomousTransferCompleteResponse */
struct _cwmp1__AutonomousTransferCompleteResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE__cwmp1__Kicked
#define SOAP_TYPE__cwmp1__Kicked (112)
/* cwmp1:Kicked */
struct _cwmp1__Kicked
{
	char *Command;	/* required element of type xsd:string */
	char *Referer;	/* required element of type xsd:string */
	char *Arg;	/* required element of type xsd:string */
	char *Next;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp1__KickedResponse
#define SOAP_TYPE__cwmp1__KickedResponse (113)
/* cwmp1:KickedResponse */
struct _cwmp1__KickedResponse
{
	char *NextURL;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp1__RequestDownload
#define SOAP_TYPE__cwmp1__RequestDownload (114)
/* cwmp1:RequestDownload */
struct _cwmp1__RequestDownload
{
	char *FileType;	/* required element of type xsd:string */
	struct cwmp1FileTypeArg *FileTypeArg;	/* required element of type ArrayOfArgStruct */
};
#endif

#ifndef SOAP_TYPE__cwmp1__RequestDownloadResponse
#define SOAP_TYPE__cwmp1__RequestDownloadResponse (117)
/* cwmp1:RequestDownloadResponse */
struct _cwmp1__RequestDownloadResponse
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_cwmp1MethodList
#define SOAP_TYPE_cwmp1MethodList (45)
/* SOAP encoded array of xsd:string schema type: */
struct cwmp1MethodList
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1EventList
#define SOAP_TYPE_cwmp1EventList (104)
/* SOAP encoded array of cwmp1:EventStruct schema type: */
struct cwmp1EventList
{
	struct cwmp1__EventStruct **__ptrEventStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1ParameterValueList
#define SOAP_TYPE_cwmp1ParameterValueList (48)
/* SOAP encoded array of cwmp1:ParameterValueStruct schema type: */
struct cwmp1ParameterValueList
{
	struct cwmp1__ParameterValueStruct **__ptrParameterValueStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1ParameterInfoList
#define SOAP_TYPE_cwmp1ParameterInfoList (58)
/* SOAP encoded array of cwmp1:ParameterInfoStruct schema type: */
struct cwmp1ParameterInfoList
{
	struct cwmp1__ParameterInfoStruct **__ptrParameterInfoStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1ParameterNames
#define SOAP_TYPE_cwmp1ParameterNames (53)
/* SOAP encoded array of xsd:string schema type: */
struct cwmp1ParameterNames
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1AccessList
#define SOAP_TYPE_cwmp1AccessList (25)
/* SOAP encoded array of xsd:string schema type: */
struct cwmp1AccessList
{
	char **__ptrstring;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1SetParameterAttributesList
#define SOAP_TYPE_cwmp1SetParameterAttributesList (61)
/* SOAP encoded array of cwmp1:SetParameterAttributesStruct schema type: */
struct cwmp1SetParameterAttributesList
{
	struct cwmp1__SetParameterAttributesStruct **__ptrSetParameterAttributesStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1ParameterAttributeList
#define SOAP_TYPE_cwmp1ParameterAttributeList (66)
/* SOAP encoded array of cwmp1:ParameterAttributeStruct schema type: */
struct cwmp1ParameterAttributeList
{
	struct cwmp1__ParameterAttributeStruct **__ptrParameterAttributeStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1TransferList
#define SOAP_TYPE_cwmp1TransferList (81)
/* SOAP encoded array of cwmp1:QueuedTransferStruct schema type: */
struct cwmp1TransferList
{
	struct cwmp1__QueuedTransferStruct **__ptrQueuedTransferStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1AllTransferList
#define SOAP_TYPE_cwmp1AllTransferList (100)
/* SOAP encoded array of cwmp1:AllQueuedTransferStruct schema type: */
struct cwmp1AllTransferList
{
	struct cwmp1__AllQueuedTransferStruct **__ptrAllQueuedTransferStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1VoucherList
#define SOAP_TYPE_cwmp1VoucherList (86)
/* SOAP encoded array of SOAP-ENC:base64 schema type: */
struct cwmp1VoucherList
{
	struct SOAP_ENC__base64 **__ptrbase64;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1OptionList
#define SOAP_TYPE_cwmp1OptionList (91)
/* SOAP encoded array of cwmp1:OptionStruct schema type: */
struct cwmp1OptionList
{
	struct cwmp1__OptionStruct **__ptrOptionStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE_cwmp1FileTypeArg
#define SOAP_TYPE_cwmp1FileTypeArg (115)
/* SOAP encoded array of cwmp1:ArgStruct schema type: */
struct cwmp1FileTypeArg
{
	struct cwmp1__ArgStruct **__ptrArgStruct;
	int __size;
};
#endif

#ifndef SOAP_TYPE__cwmp1__ID
#define SOAP_TYPE__cwmp1__ID (138)
/* Primitive cwmp1:ID schema type: */
struct _cwmp1__ID
{
	char *__item;
	char *SOAP_ENV__mustUnderstand;	/* required attribute of type xsd:string */
};
#endif

#ifndef SOAP_TYPE__cwmp1__HoldRequests
#define SOAP_TYPE__cwmp1__HoldRequests (139)
/* Primitive cwmp1:HoldRequests schema type: */
struct _cwmp1__HoldRequests
{
	enum xsd__boolean __item;
	char *SOAP_ENV__mustUnderstand;	/* required attribute of type xsd:string */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (140)
/* SOAP Header: */
struct SOAP_ENV__Header
{
	struct _cwmp1__HoldRequests *cwmp1__HoldRequests;	/* mustUnderstand */
	struct _cwmp1__ID *cwmp1__ID;	/* mustUnderstand */
};
#endif

#endif

#ifndef SOAP_TYPE___cwmp1__GetRPCMethods
#define SOAP_TYPE___cwmp1__GetRPCMethods (146)
/* Operation wrapper: */
struct __cwmp1__GetRPCMethods
{
	struct _cwmp1__GetRPCMethods *cwmp1__GetRPCMethods;	/* optional element of type cwmp1:GetRPCMethods */
};
#endif

#ifndef SOAP_TYPE___cwmp1__SetParameterValues
#define SOAP_TYPE___cwmp1__SetParameterValues (150)
/* Operation wrapper: */
struct __cwmp1__SetParameterValues
{
	struct _cwmp1__SetParameterValues *cwmp1__SetParameterValues;	/* optional element of type cwmp1:SetParameterValues */
};
#endif

#ifndef SOAP_TYPE___cwmp1__GetParameterValues
#define SOAP_TYPE___cwmp1__GetParameterValues (154)
/* Operation wrapper: */
struct __cwmp1__GetParameterValues
{
	struct _cwmp1__GetParameterValues *cwmp1__GetParameterValues;	/* optional element of type cwmp1:GetParameterValues */
};
#endif

#ifndef SOAP_TYPE___cwmp1__GetParameterNames
#define SOAP_TYPE___cwmp1__GetParameterNames (158)
/* Operation wrapper: */
struct __cwmp1__GetParameterNames
{
	struct _cwmp1__GetParameterNames *cwmp1__GetParameterNames;	/* optional element of type cwmp1:GetParameterNames */
};
#endif

#ifndef SOAP_TYPE___cwmp1__SetParameterAttributes
#define SOAP_TYPE___cwmp1__SetParameterAttributes (162)
/* Operation wrapper: */
struct __cwmp1__SetParameterAttributes
{
	struct _cwmp1__SetParameterAttributes *cwmp1__SetParameterAttributes;	/* optional element of type cwmp1:SetParameterAttributes */
};
#endif

#ifndef SOAP_TYPE___cwmp1__GetParameterAttributes
#define SOAP_TYPE___cwmp1__GetParameterAttributes (166)
/* Operation wrapper: */
struct __cwmp1__GetParameterAttributes
{
	struct _cwmp1__GetParameterAttributes *cwmp1__GetParameterAttributes;	/* optional element of type cwmp1:GetParameterAttributes */
};
#endif

#ifndef SOAP_TYPE___cwmp1__AddObject
#define SOAP_TYPE___cwmp1__AddObject (170)
/* Operation wrapper: */
struct __cwmp1__AddObject
{
	struct _cwmp1__AddObject *cwmp1__AddObject;	/* optional element of type cwmp1:AddObject */
};
#endif

#ifndef SOAP_TYPE___cwmp1__DeleteObject
#define SOAP_TYPE___cwmp1__DeleteObject (174)
/* Operation wrapper: */
struct __cwmp1__DeleteObject
{
	struct _cwmp1__DeleteObject *cwmp1__DeleteObject;	/* optional element of type cwmp1:DeleteObject */
};
#endif

#ifndef SOAP_TYPE___cwmp1__Download
#define SOAP_TYPE___cwmp1__Download (178)
/* Operation wrapper: */
struct __cwmp1__Download
{
	struct _cwmp1__Download *cwmp1__Download;	/* optional element of type cwmp1:Download */
};
#endif

#ifndef SOAP_TYPE___cwmp1__Reboot
#define SOAP_TYPE___cwmp1__Reboot (182)
/* Operation wrapper: */
struct __cwmp1__Reboot
{
	struct _cwmp1__Reboot *cwmp1__Reboot;	/* optional element of type cwmp1:Reboot */
};
#endif

#ifndef SOAP_TYPE___cwmp1__GetQueuedTransfers
#define SOAP_TYPE___cwmp1__GetQueuedTransfers (186)
/* Operation wrapper: */
struct __cwmp1__GetQueuedTransfers
{
	struct _cwmp1__GetQueuedTransfers *cwmp1__GetQueuedTransfers;	/* optional element of type cwmp1:GetQueuedTransfers */
};
#endif

#ifndef SOAP_TYPE___cwmp1__ScheduleInform
#define SOAP_TYPE___cwmp1__ScheduleInform (190)
/* Operation wrapper: */
struct __cwmp1__ScheduleInform
{
	struct _cwmp1__ScheduleInform *cwmp1__ScheduleInform;	/* optional element of type cwmp1:ScheduleInform */
};
#endif

#ifndef SOAP_TYPE___cwmp1__SetVouchers
#define SOAP_TYPE___cwmp1__SetVouchers (194)
/* Operation wrapper: */
struct __cwmp1__SetVouchers
{
	struct _cwmp1__SetVouchers *cwmp1__SetVouchers;	/* optional element of type cwmp1:SetVouchers */
};
#endif

#ifndef SOAP_TYPE___cwmp1__GetOptions
#define SOAP_TYPE___cwmp1__GetOptions (198)
/* Operation wrapper: */
struct __cwmp1__GetOptions
{
	struct _cwmp1__GetOptions *cwmp1__GetOptions;	/* optional element of type cwmp1:GetOptions */
};
#endif

#ifndef SOAP_TYPE___cwmp1__Upload
#define SOAP_TYPE___cwmp1__Upload (202)
/* Operation wrapper: */
struct __cwmp1__Upload
{
	struct _cwmp1__Upload *cwmp1__Upload;	/* optional element of type cwmp1:Upload */
};
#endif

#ifndef SOAP_TYPE___cwmp1__FactoryReset
#define SOAP_TYPE___cwmp1__FactoryReset (206)
/* Operation wrapper: */
struct __cwmp1__FactoryReset
{
	struct _cwmp1__FactoryReset *cwmp1__FactoryReset;	/* optional element of type cwmp1:FactoryReset */
};
#endif

#ifndef SOAP_TYPE___cwmp1__GetAllQueuedTransfers
#define SOAP_TYPE___cwmp1__GetAllQueuedTransfers (210)
/* Operation wrapper: */
struct __cwmp1__GetAllQueuedTransfers
{
	struct _cwmp1__GetAllQueuedTransfers *cwmp1__GetAllQueuedTransfers;	/* optional element of type cwmp1:GetAllQueuedTransfers */
};
#endif

#ifndef SOAP_TYPE___cwmp1__Inform
#define SOAP_TYPE___cwmp1__Inform (214)
/* Operation wrapper: */
struct __cwmp1__Inform
{
	struct _cwmp1__Inform *cwmp1__Inform;	/* optional element of type cwmp1:Inform */
};
#endif

#ifndef SOAP_TYPE___cwmp1__TransferComplete
#define SOAP_TYPE___cwmp1__TransferComplete (218)
/* Operation wrapper: */
struct __cwmp1__TransferComplete
{
	struct _cwmp1__TransferComplete *cwmp1__TransferComplete;	/* optional element of type cwmp1:TransferComplete */
};
#endif

#ifndef SOAP_TYPE___cwmp1__AutonomousTransferComplete
#define SOAP_TYPE___cwmp1__AutonomousTransferComplete (222)
/* Operation wrapper: */
struct __cwmp1__AutonomousTransferComplete
{
	struct _cwmp1__AutonomousTransferComplete *cwmp1__AutonomousTransferComplete;	/* optional element of type cwmp1:AutonomousTransferComplete */
};
#endif

#ifndef SOAP_TYPE___cwmp1__Kicked
#define SOAP_TYPE___cwmp1__Kicked (226)
/* Operation wrapper: */
struct __cwmp1__Kicked
{
	struct _cwmp1__Kicked *cwmp1__Kicked;	/* optional element of type cwmp1:Kicked */
};
#endif

#ifndef SOAP_TYPE___cwmp1__RequestDownload
#define SOAP_TYPE___cwmp1__RequestDownload (230)
/* Operation wrapper: */
struct __cwmp1__RequestDownload
{
	struct _cwmp1__RequestDownload *cwmp1__RequestDownload;	/* optional element of type cwmp1:RequestDownload */
};
#endif

#ifndef SOAP_TYPE___cwmp1__Fault
#define SOAP_TYPE___cwmp1__Fault (234)
/* Operation wrapper: */
struct __cwmp1__Fault
{
	struct _cwmp1__Fault *cwmp1__Fault;	/* optional element of type cwmp1:Fault */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (235)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (237)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (239)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (240)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif

#ifndef SOAP_TYPE_xsd__anySimpleType
#define SOAP_TYPE_xsd__anySimpleType (11)
typedef char *xsd__anySimpleType;
#endif

#ifndef SOAP_TYPE_cwmp1__FaultCodeType
#define SOAP_TYPE_cwmp1__FaultCodeType (13)
typedef char *cwmp1__FaultCodeType;
#endif

#ifndef SOAP_TYPE_cwmp1__ParameterKeyType
#define SOAP_TYPE_cwmp1__ParameterKeyType (14)
typedef char *cwmp1__ParameterKeyType;
#endif

#ifndef SOAP_TYPE_cwmp1__CommandKeyType
#define SOAP_TYPE_cwmp1__CommandKeyType (15)
typedef char *cwmp1__CommandKeyType;
#endif

#ifndef SOAP_TYPE_cwmp1__ObjectNameType
#define SOAP_TYPE_cwmp1__ObjectNameType (16)
typedef char *cwmp1__ObjectNameType;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__GetRPCMethods(struct soap*, struct _cwmp1__GetRPCMethods *cwmp1__GetRPCMethods, struct _cwmp1__GetRPCMethodsResponse *cwmp1__GetRPCMethodsResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__SetParameterValues(struct soap*, struct _cwmp1__SetParameterValues *cwmp1__SetParameterValues, struct _cwmp1__SetParameterValuesResponse *cwmp1__SetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__GetParameterValues(struct soap*, struct _cwmp1__GetParameterValues *cwmp1__GetParameterValues, struct _cwmp1__GetParameterValuesResponse *cwmp1__GetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__GetParameterNames(struct soap*, struct _cwmp1__GetParameterNames *cwmp1__GetParameterNames, struct _cwmp1__GetParameterNamesResponse *cwmp1__GetParameterNamesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__SetParameterAttributes(struct soap*, struct _cwmp1__SetParameterAttributes *cwmp1__SetParameterAttributes, struct _cwmp1__SetParameterAttributesResponse *cwmp1__SetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__GetParameterAttributes(struct soap*, struct _cwmp1__GetParameterAttributes *cwmp1__GetParameterAttributes, struct _cwmp1__GetParameterAttributesResponse *cwmp1__GetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__AddObject(struct soap*, struct _cwmp1__AddObject *cwmp1__AddObject, struct _cwmp1__AddObjectResponse *cwmp1__AddObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__DeleteObject(struct soap*, struct _cwmp1__DeleteObject *cwmp1__DeleteObject, struct _cwmp1__DeleteObjectResponse *cwmp1__DeleteObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__Download(struct soap*, struct _cwmp1__Download *cwmp1__Download, struct _cwmp1__DownloadResponse *cwmp1__DownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__Reboot(struct soap*, struct _cwmp1__Reboot *cwmp1__Reboot, struct _cwmp1__RebootResponse *cwmp1__RebootResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__GetQueuedTransfers(struct soap*, struct _cwmp1__GetQueuedTransfers *cwmp1__GetQueuedTransfers, struct _cwmp1__GetQueuedTransfersResponse *cwmp1__GetQueuedTransfersResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__ScheduleInform(struct soap*, struct _cwmp1__ScheduleInform *cwmp1__ScheduleInform, struct _cwmp1__ScheduleInformResponse *cwmp1__ScheduleInformResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__SetVouchers(struct soap*, struct _cwmp1__SetVouchers *cwmp1__SetVouchers, struct _cwmp1__SetVouchersResponse *cwmp1__SetVouchersResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__GetOptions(struct soap*, struct _cwmp1__GetOptions *cwmp1__GetOptions, struct _cwmp1__GetOptionsResponse *cwmp1__GetOptionsResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__Upload(struct soap*, struct _cwmp1__Upload *cwmp1__Upload, struct _cwmp1__UploadResponse *cwmp1__UploadResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__FactoryReset(struct soap*, struct _cwmp1__FactoryReset *cwmp1__FactoryReset, struct _cwmp1__FactoryResetResponse *cwmp1__FactoryResetResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__GetAllQueuedTransfers(struct soap*, struct _cwmp1__GetAllQueuedTransfers *cwmp1__GetAllQueuedTransfers, struct _cwmp1__GetAllQueuedTransfersResponse *cwmp1__GetAllQueuedTransfersResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__Inform(struct soap*, struct _cwmp1__Inform *cwmp1__Inform, struct _cwmp1__InformResponse *cwmp1__InformResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__TransferComplete(struct soap*, struct _cwmp1__TransferComplete *cwmp1__TransferComplete, struct _cwmp1__TransferCompleteResponse *cwmp1__TransferCompleteResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__AutonomousTransferComplete(struct soap*, struct _cwmp1__AutonomousTransferComplete *cwmp1__AutonomousTransferComplete, struct _cwmp1__AutonomousTransferCompleteResponse *cwmp1__AutonomousTransferCompleteResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__Kicked(struct soap*, struct _cwmp1__Kicked *cwmp1__Kicked, struct _cwmp1__KickedResponse *cwmp1__KickedResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__RequestDownload(struct soap*, struct _cwmp1__RequestDownload *cwmp1__RequestDownload, struct _cwmp1__RequestDownloadResponse *cwmp1__RequestDownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 __cwmp1__Fault(struct soap*, struct _cwmp1__Fault *cwmp1__Fault);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetRPCMethods(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__SetParameterValues(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetParameterValues(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetParameterNames(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__SetParameterAttributes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetParameterAttributes(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__AddObject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__DeleteObject(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__Download(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__Reboot(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetQueuedTransfers(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__ScheduleInform(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__SetVouchers(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetOptions(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__Upload(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__FactoryReset(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__GetAllQueuedTransfers(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__Inform(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__TransferComplete(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__AutonomousTransferComplete(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__Kicked(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__RequestDownload(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___cwmp1__Fault(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetRPCMethods(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetRPCMethods *cwmp1__GetRPCMethods, struct _cwmp1__GetRPCMethodsResponse *cwmp1__GetRPCMethodsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__SetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__SetParameterValues *cwmp1__SetParameterValues, struct _cwmp1__SetParameterValuesResponse *cwmp1__SetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetParameterValues(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetParameterValues *cwmp1__GetParameterValues, struct _cwmp1__GetParameterValuesResponse *cwmp1__GetParameterValuesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetParameterNames(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetParameterNames *cwmp1__GetParameterNames, struct _cwmp1__GetParameterNamesResponse *cwmp1__GetParameterNamesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__SetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__SetParameterAttributes *cwmp1__SetParameterAttributes, struct _cwmp1__SetParameterAttributesResponse *cwmp1__SetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetParameterAttributes(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetParameterAttributes *cwmp1__GetParameterAttributes, struct _cwmp1__GetParameterAttributesResponse *cwmp1__GetParameterAttributesResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__AddObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__AddObject *cwmp1__AddObject, struct _cwmp1__AddObjectResponse *cwmp1__AddObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__DeleteObject(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__DeleteObject *cwmp1__DeleteObject, struct _cwmp1__DeleteObjectResponse *cwmp1__DeleteObjectResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__Download(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__Download *cwmp1__Download, struct _cwmp1__DownloadResponse *cwmp1__DownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__Reboot(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__Reboot *cwmp1__Reboot, struct _cwmp1__RebootResponse *cwmp1__RebootResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetQueuedTransfers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetQueuedTransfers *cwmp1__GetQueuedTransfers, struct _cwmp1__GetQueuedTransfersResponse *cwmp1__GetQueuedTransfersResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__ScheduleInform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__ScheduleInform *cwmp1__ScheduleInform, struct _cwmp1__ScheduleInformResponse *cwmp1__ScheduleInformResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__SetVouchers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__SetVouchers *cwmp1__SetVouchers, struct _cwmp1__SetVouchersResponse *cwmp1__SetVouchersResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetOptions(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetOptions *cwmp1__GetOptions, struct _cwmp1__GetOptionsResponse *cwmp1__GetOptionsResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__Upload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__Upload *cwmp1__Upload, struct _cwmp1__UploadResponse *cwmp1__UploadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__FactoryReset(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__FactoryReset *cwmp1__FactoryReset, struct _cwmp1__FactoryResetResponse *cwmp1__FactoryResetResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__GetAllQueuedTransfers(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__GetAllQueuedTransfers *cwmp1__GetAllQueuedTransfers, struct _cwmp1__GetAllQueuedTransfersResponse *cwmp1__GetAllQueuedTransfersResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__Inform(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__Inform *cwmp1__Inform, struct _cwmp1__InformResponse *cwmp1__InformResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__TransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__TransferComplete *cwmp1__TransferComplete, struct _cwmp1__TransferCompleteResponse *cwmp1__TransferCompleteResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__AutonomousTransferComplete(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__AutonomousTransferComplete *cwmp1__AutonomousTransferComplete, struct _cwmp1__AutonomousTransferCompleteResponse *cwmp1__AutonomousTransferCompleteResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__Kicked(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__Kicked *cwmp1__Kicked, struct _cwmp1__KickedResponse *cwmp1__KickedResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_call___cwmp1__RequestDownload(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__RequestDownload *cwmp1__RequestDownload, struct _cwmp1__RequestDownloadResponse *cwmp1__RequestDownloadResponse);

SOAP_FMAC5 int SOAP_FMAC6 soap_send___cwmp1__Fault(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _cwmp1__Fault *cwmp1__Fault);

SOAP_FMAC5 int SOAP_FMAC6 soap_recv___cwmp1__Fault(struct soap *soap, struct __cwmp1__Fault *_param_1);


#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
